import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  terraform: [{type: 'autogenerated', dirName: 'terraform'}],
  gitops: [{type: 'autogenerated', dirName: 'gitops'}],
  scripting: [{type: 'autogenerated', dirName: 'scripting'}],
};

export default sidebars;
