import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  terraform: [
    {
      type: 'category',
      label: 'Terraform',
      link: {type: 'generated-index', description: 'Materiales de Terraform'},
      items: [{type: 'autogenerated', dirName: 'terraform'}],
    },
  ],
  gitops: [
    {
      type: 'category',
      label: 'GitOps',
      link: {type: 'generated-index', description: 'Materiales de GitOps'},
      items: [{type: 'autogenerated', dirName: 'gitops'}],
    },
  ],
  scripting: [
    {
      type: 'category',
      label: 'Scripting',
      link: {type: 'generated-index', description: 'Materiales de Scripting'},
      items: [{type: 'autogenerated', dirName: 'scripting'}],
    },
  ],
};

export default sidebars;
