import type { TestConfig } from '@site/src/components/test/types';

export const testFundamentos: TestConfig = {
  id: 'go-fundamentos',
  title: 'Fundamentos de GitOps y Kubernetes',
  numberOfQuestions: 10,
  time: 15,
  pointsType: 'over10',
  minForPass: 6,
  onTimeUp: 'warn',
  questions: [
    {
      id: 'go-f-1',
      title: '¿Cuál de estos NO es uno de los cuatro principios de OpenGitOps?',
      type: 'select',
      points: 1,
      explanation: 'Los cuatro principios son: declarativo, versionado e inmutable, pull automático y reconciliación continua. Usar una herramienta concreta (ArgoCD, Flux…) no es un principio: OpenGitOps es agnóstico de herramientas.',
      answers: ['Declarativo', 'Versionado e inmutable', 'Reconciliación continua', 'Usar ArgoCD como agente'],
      correctAnswer: 3,
    },
    {
      id: 'go-f-2',
      title: 'En el modelo pull, ¿quién aplica los cambios en el clúster?',
      type: 'select',
      points: 1,
      explanation: 'En GitOps un agente que vive dentro del clúster (ArgoCD, Flux) observa Git y aplica los cambios. La CI solo construye y publica artefactos.',
      answers: ['El pipeline de CI con kubectl apply', 'Un agente dentro del clúster que observa Git', 'El desarrollador desde su portátil', 'El registry de imágenes'],
      correctAnswer: 1,
    },
    {
      id: 'go-f-3',
      title: '¿Por qué el modelo pull reduce la superficie de ataque?',
      type: 'select',
      points: 2,
      explanation: 'Las credenciales de Kubernetes no salen del clúster: el agente inicia la conexión hacia Git. En el modelo push, la CI guarda un KUBECONFIG con permisos de escritura.',
      answers: [
        'Porque cifra el state de Kubernetes',
        'Porque las credenciales del clúster nunca salen de él',
        'Porque impide hacer kubectl desde cualquier sitio',
        'Porque Git firma todos los commits automáticamente',
      ],
      correctAnswer: 1,
    },
    {
      id: 'go-f-4',
      title: '¿Qué es el configuration drift?',
      type: 'select',
      points: 1,
      explanation: 'Es la divergencia entre el estado deseado (en Git) y el estado real del clúster, por ejemplo tras un kubectl edit o kubectl scale manual.',
      answers: [
        'Un retraso en el polling de ArgoCD',
        'La diferencia entre el estado declarado en Git y el real del clúster',
        'Un conflicto de merge en el repositorio de configuración',
        'La latencia entre dos réplicas de un Deployment',
      ],
      correctAnswer: 1,
    },
    {
      id: 'go-f-5',
      title: '¿En qué casos sigue siendo razonable el modelo push?',
      type: 'multiselect',
      points: 2,
      explanation: 'Push encaja en proyectos pequeños, despliegues fuera de Kubernetes (VMs, PaaS) y clústeres efímeros por PR. En entornos regulados con varios equipos, GitOps aporta trazabilidad y detección de drift.',
      answers: [
        'Desplegar en una VM o un PaaS sin Kubernetes',
        'Un clúster efímero que se crea y destruye en cada PR',
        'Producción regulada con varios equipos haciendo cambios',
        'Un equipo que empieza con CI/CD y necesita resultados rápidos',
      ],
      correctAnswer: [0, 1, 3],
    },
    {
      id: 'go-f-6',
      title: '¿Qué objeto de Kubernetes da una IP y un nombre DNS estables a un conjunto de pods?',
      type: 'select',
      points: 1,
      explanation: 'Un Service selecciona pods por labels y les da una IP virtual y un nombre DNS estables, aunque los pods cambien.',
      answers: ['Deployment', 'ReplicaSet', 'Service', 'ConfigMap'],
      correctAnswer: 2,
    },
    {
      id: 'go-f-7',
      title: 'Borras a mano un pod de un Deployment con 3 réplicas. ¿Qué ocurre?',
      type: 'select',
      points: 1,
      explanation: 'El ReplicaSet del Deployment detecta que hay 2 pods en lugar de 3 y crea uno nuevo. Es reconciliación dentro de Kubernetes, igual que ArgoCD la hace con Git.',
      answers: ['El Deployment queda con 2 réplicas', 'El ReplicaSet crea un pod nuevo', 'El Deployment se borra', 'Kubernetes pide confirmación'],
      correctAnswer: 1,
    },
    {
      id: 'go-f-8',
      title: '¿Por qué un Secret de Kubernetes no se puede subir a Git tal cual?',
      type: 'select',
      points: 1,
      explanation: 'Los valores de un Secret van en base64, que es una codificación, no un cifrado. Cualquiera con acceso al repositorio podría leerlos.',
      answers: ['Porque ocupa demasiado', 'Porque base64 no es cifrado', 'Porque kubectl no lo permite', 'Porque ArgoCD ignora los Secrets'],
      correctAnswer: 1,
    },
    {
      id: 'go-f-9',
      title: '¿Qué comando aplica un overlay de Kustomize directamente con kubectl?',
      type: 'select',
      points: 1,
      explanation: 'kubectl integra Kustomize: -k apunta a un directorio con kustomization.yaml. kubectl kustomize solo renderiza el resultado.',
      answers: ['kubectl apply -f k8s/overlays/dev', 'kubectl apply -k k8s/overlays/dev', 'kubectl kustomize --apply dev', 'kubectl patch -k dev'],
      correctAnswer: 1,
    },
    {
      id: 'go-f-10',
      title: '¿Qué dos herramientas GitOps son proyectos graduados de la CNCF?',
      type: 'multiselect',
      points: 2,
      explanation: 'ArgoCD y Flux son proyectos graduados de la CNCF. Jenkins X pertenece a la CD Foundation.',
      answers: ['ArgoCD', 'Flux', 'Jenkins X', 'GitHub Actions'],
      correctAnswer: [0, 1],
    },
  ],
};

export const testGithubActions: TestConfig = {
  id: 'go-actions',
  title: 'GitHub Actions',
  numberOfQuestions: 10,
  time: 15,
  pointsType: 'over10',
  minForPass: 6,
  onTimeUp: 'warn',
  questions: [
    {
      id: 'go-a-1',
      title: '¿Dónde tiene que estar un workflow de GitHub Actions?',
      type: 'select',
      points: 1,
      explanation: 'Los workflows son ficheros YAML dentro de .github/workflows/ en el repositorio.',
      answers: ['.github/actions/', '.github/workflows/', '.workflows/', 'ci/github.yml'],
      correctAnswer: 1,
    },
    {
      id: 'go-a-2',
      title: 'Por defecto, ¿cómo se ejecutan los jobs de un workflow?',
      type: 'select',
      points: 1,
      explanation: 'Los jobs corren en paralelo, cada uno en un runner limpio. needs crea dependencias y convierte el conjunto en un DAG.',
      answers: ['En serie, en el orden del fichero', 'En paralelo, salvo que uses needs', 'En el mismo runner, compartiendo disco', 'Solo uno por workflow'],
      correctAnswer: 1,
    },
    {
      id: 'go-a-3',
      title: 'Una matriz con node-version: [18, 20, 22] y os: [ubuntu-latest, macos-latest], ¿cuántos jobs genera?',
      type: 'select',
      points: 1,
      explanation: 'La matriz multiplica las combinaciones: 3 versiones × 2 sistemas = 6 jobs.',
      answers: ['2', '3', '5', '6'],
      correctAnswer: 3,
    },
    {
      id: 'go-a-4',
      title: '¿Cuál es la forma segura de usar el título de un PR en un step?',
      type: 'select',
      points: 2,
      explanation: 'Interpolar ${{ github.event.* }} dentro de run permite inyección de comandos. Hay que pasarlo por env y usar la variable entre comillas.',
      answers: [
        'run: echo "${{ github.event.pull_request.title }}"',
        'env: TITLE: ${{ github.event.pull_request.title }} y run: echo "$TITLE"',
        'run: echo ${{ github.event.pull_request.title }} | sanitize',
        'Guardarlo en un secret',
      ],
      correctAnswer: 1,
    },
    {
      id: 'go-a-5',
      title: '¿Cómo pasas ficheros de un job a otro?',
      type: 'select',
      points: 1,
      explanation: 'Los jobs no comparten sistema de ficheros: se usan actions/upload-artifact y actions/download-artifact.',
      answers: ['Con variables de entorno', 'Con upload-artifact y download-artifact', 'Escribiendo en /tmp', 'Con actions/cache siempre'],
      correctAnswer: 1,
    },
    {
      id: 'go-a-6',
      title: '¿Qué aporta un environment con revisores obligatorios?',
      type: 'select',
      points: 1,
      explanation: 'El job que declara ese environment espera a que un revisor apruebe antes de ejecutarse. También permite secrets por entorno.',
      answers: ['Más minutos de runner', 'Una aprobación manual antes de ejecutar el job', 'Caché compartida entre repos', 'Cifrado de los logs'],
      correctAnswer: 1,
    },
    {
      id: 'go-a-7',
      title: '¿Qué diferencia hay entre una composite action y un reusable workflow?',
      type: 'select',
      points: 2,
      explanation: 'Una composite action agrupa steps que se usan dentro de un job. Un reusable workflow (on: workflow_call) contiene jobs completos y se llama desde otro workflow.',
      answers: [
        'Ninguna, son sinónimos',
        'La composite agrupa steps; el reusable workflow agrupa jobs completos',
        'La composite solo funciona en Windows',
        'El reusable workflow no admite inputs',
      ],
      correctAnswer: 1,
    },
    {
      id: 'go-a-8',
      title: '¿Por qué hay que fijar las Actions a una versión (@v5) en lugar de @main?',
      type: 'select',
      points: 1,
      explanation: 'Un cambio en la rama principal de la Action podría romper o comprometer tu pipeline sin aviso. Fijar la versión (o el SHA) lo hace reproducible.',
      answers: ['Porque @main no existe', 'Para que un cambio en la Action no rompa tu pipeline sin aviso', 'Porque es más rápido', 'Porque GitHub lo exige'],
      correctAnswer: 1,
    },
    {
      id: 'go-a-9',
      title: 'En el pipeline de la wiki del curso, ¿qué ocurre en un pull request?',
      type: 'select',
      points: 1,
      explanation: 'El workflow construye y prueba el sitio en los PR, pero la subida del artefacto y el despliegue solo ocurren en push a main.',
      answers: ['Se publica el sitio en GitHub Pages', 'Se construye y se prueba, pero no se publica', 'No se ejecuta nada', 'Se despliega en un entorno de preview'],
      correctAnswer: 1,
    },
    {
      id: 'go-a-10',
      title: '¿Qué permisos necesita un workflow para publicar en GitHub Pages con actions/deploy-pages?',
      type: 'multiselect',
      points: 2,
      explanation: 'deploy-pages necesita pages: write y id-token: write (verifica el origen del despliegue con OIDC). No hace falta un token personal.',
      answers: ['pages: write', 'id-token: write', 'packages: write', 'Un PAT guardado en secrets'],
      correctAnswer: [0, 1],
    },
  ],
};

export const testArgoCD: TestConfig = {
  id: 'go-argocd',
  title: 'ArgoCD y multi-entorno',
  numberOfQuestions: 10,
  time: 15,
  pointsType: 'over10',
  minForPass: 6,
  onTimeUp: 'warn',
  questions: [
    {
      id: 'go-c-1',
      title: '¿Qué componente de ArgoCD compara el estado renderizado con el del clúster y reconcilia?',
      type: 'select',
      points: 1,
      explanation: 'El Application Controller compara y reconcilia. El Repo Server clona y renderiza los manifiestos; el API Server sirve la UI y el CLI.',
      answers: ['Repo Server', 'Application Controller', 'API Server', 'Dex'],
      correctAnswer: 1,
    },
    {
      id: 'go-c-2',
      title: 'Desde Argo CD 3, ¿cómo se aplica el manifiesto de instalación?',
      type: 'select',
      points: 2,
      explanation: 'Algunas CRD de Argo CD superan el límite de tamaño de la anotación que usa kubectl apply en el lado del cliente, así que se instala con server-side apply.',
      answers: [
        'kubectl create -f install.yaml',
        'kubectl apply -n argocd --server-side --force-conflicts -f install.yaml',
        'helm install argocd install.yaml',
        'argocd install --namespace argocd',
      ],
      correctAnswer: 1,
    },
    {
      id: 'go-c-3',
      title: '¿Qué hace prune: true en la syncPolicy?',
      type: 'select',
      points: 1,
      explanation: 'prune borra del clúster los recursos que ya no están en Git. Sin él, los recursos huérfanos se quedan.',
      answers: ['Revierte los cambios manuales', 'Borra del clúster lo que ya no está en Git', 'Limpia el historial de Git', 'Elimina pods en CrashLoopBackOff'],
      correctAnswer: 1,
    },
    {
      id: 'go-c-4',
      title: 'Alguien ejecuta kubectl scale a mano en una app con automated + selfHeal. ¿Qué pasa?',
      type: 'select',
      points: 1,
      explanation: 'ArgoCD detecta el drift (OutOfSync) y selfHeal lo revierte al estado de Git.',
      answers: ['El cambio se queda', 'ArgoCD lo revierte al valor de Git', 'ArgoCD hace commit del cambio en Git', 'La app pasa a Degraded para siempre'],
      correctAnswer: 1,
    },
    {
      id: 'go-c-5',
      title: 'Una app puede estar a la vez…',
      type: 'select',
      points: 1,
      explanation: 'Sync status y health status son independientes: una app puede coincidir con Git (Synced) y tener pods fallando (Degraded).',
      answers: ['Synced y Degraded', 'OutOfSync y Missing, nunca otra combinación', 'Solo Synced y Healthy', 'Healthy y Unknown a la vez'],
      correctAnswer: 0,
    },
    {
      id: 'go-c-6',
      title: '¿Qué herramienta del curso cifra un Secret con la clave pública del clúster para poder subirlo a Git?',
      type: 'select',
      points: 1,
      explanation: 'Sealed Secrets (kubeseal) cifra con la clave pública del clúster; solo el controlador del clúster puede descifrarlo.',
      answers: ['External Secrets Operator', 'Sealed Secrets', 'Vault Agent Injector', 'Kustomize secretGenerator'],
      correctAnswer: 1,
    },
    {
      id: 'go-c-7',
      title: 'En Kustomize, ¿dónde va lo común a todos los entornos?',
      type: 'select',
      points: 1,
      explanation: 'La base guarda lo común; cada overlay la referencia con resources: [../../base] y aplica sus parches.',
      answers: ['En cada overlay, copiado', 'En la base', 'En el Application de ArgoCD', 'En un ConfigMap'],
      correctAnswer: 1,
    },
    {
      id: 'go-c-8',
      title: '¿Qué campo de kustomization.yaml sustituye a patchesStrategicMerge y patchesJson6902 en Kustomize 5?',
      type: 'select',
      points: 2,
      explanation: 'patches admite tanto parches estratégicos como JSON 6902, con un target opcional. Los campos antiguos están deprecados.',
      answers: ['overlays', 'patches', 'transformers', 'replacements'],
      correctAnswer: 1,
    },
    {
      id: 'go-c-9',
      title: '¿Qué recurso genera varias Applications (dev, staging, prod) desde una sola plantilla?',
      type: 'select',
      points: 1,
      explanation: 'Un ApplicationSet usa generadores (List, Git, Cluster, Matrix…) para crear Applications a partir de una plantilla.',
      answers: ['AppProject', 'ApplicationSet', 'Rollout', 'Kustomization'],
      correctAnswer: 1,
    },
    {
      id: 'go-c-10',
      title: 'En el repo de clase, ¿por qué la Application de prod no tiene syncPolicy.automated?',
      type: 'select',
      points: 1,
      explanation: 'En producción se prefiere revisar el diff y sincronizar a mano (argocd app sync o el botón SYNC), mientras dev y staging se sincronizan solos.',
      answers: ['Porque ArgoCD no permite sync automático en prod', 'Para revisar el diff y sincronizar a mano', 'Porque prod usa Helm', 'Por un error del repositorio'],
      correctAnswer: 1,
    },
  ],
};

export const testEstrategias: TestConfig = {
  id: 'go-estrategias',
  title: 'Estrategias de despliegue y rollback',
  numberOfQuestions: 8,
  time: 12,
  pointsType: 'over10',
  minForPass: 6,
  onTimeUp: 'warn',
  questions: [
    {
      id: 'go-e-1',
      title: '¿Qué estrategia tiene downtime?',
      type: 'select',
      points: 1,
      explanation: 'Recreate borra todos los pods antiguos antes de crear los nuevos, así que hay un periodo sin servicio.',
      answers: ['Rolling update', 'Recreate', 'Blue-green', 'Canary'],
      correctAnswer: 1,
    },
    {
      id: 'go-e-2',
      title: 'Con 4 réplicas, maxUnavailable: 1 y maxSurge: 1, ¿cuántos pods puede haber como máximo durante un rolling update?',
      type: 'select',
      points: 2,
      explanation: 'maxSurge permite 1 pod por encima de las réplicas deseadas: 4 + 1 = 5.',
      answers: ['3', '4', '5', '8'],
      correctAnswer: 2,
    },
    {
      id: 'go-e-3',
      title: '¿Por qué es clave la readinessProbe en un rolling update?',
      type: 'select',
      points: 1,
      explanation: 'Sin readinessProbe, el Service envía tráfico a pods que aún están arrancando.',
      answers: ['Porque reinicia los pods colgados', 'Para no enviar tráfico a pods que aún no están listos', 'Porque acelera la descarga de la imagen', 'Porque sustituye a la livenessProbe'],
      correctAnswer: 1,
    },
    {
      id: 'go-e-4',
      title: 'En blue-green con Argo Rollouts, ¿qué hace kubectl argo rollouts promote?',
      type: 'select',
      points: 1,
      explanation: 'Conmuta el Service activo a la nueva versión (green) de golpe; la antigua se mantiene scaleDownDelaySeconds por si hay que volver.',
      answers: ['Borra la versión antigua', 'Conmuta todo el tráfico a la nueva versión', 'Sube el canary al 10 %', 'Hace git push'],
      correctAnswer: 1,
    },
    {
      id: 'go-e-5',
      title: 'Un canary con un AnalysisTemplate detecta una tasa de éxito del 90 % (umbral 95 %). ¿Qué pasa?',
      type: 'select',
      points: 2,
      explanation: 'El análisis falla y Argo Rollouts aborta el rollout, devolviendo el tráfico a la versión estable.',
      answers: ['Sigue al siguiente paso', 'Aborta y devuelve el tráfico a la versión estable', 'Pausa para siempre sin avisar', 'Borra el AnalysisTemplate'],
      correctAnswer: 1,
    },
    {
      id: 'go-e-6',
      title: '¿Cuál es la forma recomendada de hacer rollback en GitOps?',
      type: 'select',
      points: 1,
      explanation: 'git revert crea un commit nuevo que deshace el cambio y deja rastro; ArgoCD lo aplica como cualquier otro cambio.',
      answers: ['git reset --hard y push --force', 'git revert y push', 'kubectl rollout undo', 'Borrar la Application'],
      correctAnswer: 1,
    },
    {
      id: 'go-e-7',
      title: '¿Cuándo rechaza ArgoCD un argocd app rollback?',
      type: 'select',
      points: 2,
      explanation: 'Con sincronización automática activada, ArgoCD rechaza el rollback (volvería a aplicar Git en el siguiente ciclo). Solo funciona en apps con sync manual.',
      answers: ['Nunca', 'Cuando la Application tiene sincronización automática', 'Cuando la app está Healthy', 'Cuando hay más de 10 revisiones'],
      correctAnswer: 1,
    },
    {
      id: 'go-e-8',
      title: 'Un nodo falla y un pod queda en CrashLoopBackOff sin cambios de versión. ¿Rollback o redeploy?',
      type: 'select',
      points: 1,
      explanation: 'Si la causa no es la versión, basta con un redeploy (kubectl rollout restart); un rollback no arreglaría nada.',
      answers: ['Rollback', 'Redeploy', 'Ninguno: borrar el namespace', 'Cambiar a Recreate'],
      correctAnswer: 1,
    },
  ],
};

export const testPipeline: TestConfig = {
  id: 'go-pipeline',
  title: 'Pipeline end-to-end',
  numberOfQuestions: 8,
  time: 12,
  pointsType: 'over10',
  minForPass: 6,
  onTimeUp: 'warn',
  questions: [
    {
      id: 'go-p-1',
      title: 'En el app repo de clase, ¿qué dispara el workflow ci.yaml?',
      type: 'select',
      points: 1,
      explanation: 'El workflow se dispara al hacer push de un tag v* (por ejemplo v1.2.0): cada despliegue corresponde a una versión con nombre.',
      answers: ['Cada push a main', 'Un tag v*', 'Un cron diario', 'Abrir un issue'],
      correctAnswer: 1,
    },
    {
      id: 'go-p-2',
      title: '¿Qué cambia el job update-manifests en el config repo?',
      type: 'select',
      points: 1,
      explanation: 'Sustituye newTag en k8s/base/kustomization.yaml por la versión del tag y hace commit y push.',
      answers: ['La imagen en deployment.yaml de cada overlay', 'newTag en k8s/base/kustomization.yaml', 'El número de réplicas de prod', 'La Application de ArgoCD'],
      correctAnswer: 1,
    },
    {
      id: 'go-p-3',
      title: 'Como el cambio va a la base, ¿qué entornos se actualizan solos?',
      type: 'select',
      points: 2,
      explanation: 'dev y staging tienen sincronización automática y se actualizan; prod espera a un sync manual.',
      answers: ['Solo dev', 'dev y staging; prod espera a un sync manual', 'Los tres', 'Ninguno hasta hacer merge'],
      correctAnswer: 1,
    },
    {
      id: 'go-p-4',
      title: '¿Toca la CI el clúster de Kubernetes en este flujo?',
      type: 'select',
      points: 1,
      explanation: 'No: la CI construye, publica y actualiza Git. ArgoCD, dentro del clúster, aplica los cambios.',
      answers: ['Sí, con kubectl apply', 'No, solo actualiza Git', 'Solo en prod', 'Solo si falla ArgoCD'],
      correctAnswer: 1,
    },
    {
      id: 'go-p-5',
      title: '¿Qué token es más adecuado para que la CI escriba en el config repo?',
      type: 'select',
      points: 2,
      explanation: 'Un fine-grained token con Contents: Read and write solo sobre ese repo, o mejor una GitHub App instalada en él. Un PAT clásico da acceso a todos tus repositorios.',
      answers: ['GITHUB_TOKEN del app repo', 'Un PAT clásico con scope repo', 'Un fine-grained token o una GitHub App limitados al config repo', 'La contraseña de la cuenta'],
      correctAnswer: 2,
    },
    {
      id: 'go-p-6',
      title: '¿Por qué separar el app repo del config repo?',
      type: 'multiselect',
      points: 2,
      explanation: 'Historial de configuración limpio, permisos distintos (el config repo exige revisión) y ArgoCD solo necesita leer el config repo. Además el app repo no se llena de commits de tag.',
      answers: [
        'Historial de configuración limpio y auditable',
        'Permisos distintos para cada repositorio',
        'ArgoCD solo necesita acceso de lectura al config repo',
        'Porque ArgoCD no puede leer código Go',
      ],
      correctAnswer: [0, 1, 2],
    },
    {
      id: 'go-p-7',
      title: '¿Por qué no desplegar :latest en producción?',
      type: 'select',
      points: 1,
      explanation: 'latest cambia sin que Git lo registre: no sabes qué código corre. Una versión o el SHA son inmutables.',
      answers: ['Porque ocupa más', 'Porque puede cambiar sin quedar registrado en Git', 'Porque GHCR no lo admite', 'Porque ArgoCD lo ignora'],
      correctAnswer: 1,
    },
    {
      id: 'go-p-8',
      title: '¿Qué hace git diff --cached --quiet antes del commit en update-manifests?',
      type: 'select',
      points: 1,
      explanation: 'Devuelve 0 si no hay cambios preparados; en ese caso el step sale sin crear un commit vacío.',
      answers: ['Muestra el diff', 'Evita un commit vacío si el tag ya estaba puesto', 'Firma el commit', 'Hace push'],
      correctAnswer: 1,
    },
  ],
};
