import type { TestConfig } from '@site/src/components/test/types';

export const testIntroduction: TestConfig = {
  id: 'tf-intro',
  title: 'Introducción a Terraform',
  numberOfQuestions: 5,
  time: 10,
  pointsType: 'over10',
  minForPass: 6,
  onTimeUp: 'warn',
  questions: [
    {
      id: 'intro-1',
      title: '¿Cuál es la función principal de terraform plan?',
      type: 'select',
      points: 2,
      explanation: 'terraform plan genera un plan de ejecución que muestra qué acciones tomará Terraform sin aplicar cambios reales.',
      answers: [
        'Aplicar cambios en la infraestructura',
        'Mostrar una preview de los cambios sin aplicarlos',
        'Destruir todos los recursos',
        'Inicializar el directorio de trabajo',
      ],
      correctAnswer: 1,
    },
    {
      id: 'intro-2',
      title: '¿Qué archivos utiliza Terraform para definir infraestructura?',
      type: 'select',
      points: 2,
      explanation: 'Terraform utiliza archivos con extensión .tf escritos en HCL (HashiCorp Configuration Language).',
      answers: [
        'Archivos .yaml',
        'Archivos .tf',
        'Archivos .json exclusivamente',
        'Archivos .xml',
      ],
      correctAnswer: 1,
    },
    {
      id: 'intro-3',
      title: '¿Cuáles son ventajas de Infrastructure as Code? (Selecciona todas las correctas)',
      type: 'multiselect',
      points: 3,
      explanation: 'IaC permite versionado, reproducibilidad y automatización de la infraestructura.',
      answers: [
        'Versionado con Git',
        'Reproducibilidad entre entornos',
        'Requiere acceso manual al portal cloud',
        'Automatización en pipelines CI/CD',
      ],
      correctAnswer: [0, 1, 3],
    },
    {
      id: 'intro-4',
      title: 'Une cada comando de Terraform con su función',
      type: 'match',
      points: 4,
      explanation: 'init descarga providers, plan muestra preview, apply ejecuta cambios, destroy elimina recursos.',
      matchPairs: [
        { left: 'terraform init', right: 'Descarga providers y módulos' },
        { left: 'terraform plan', right: 'Muestra preview de cambios' },
        { left: 'terraform apply', right: 'Ejecuta los cambios' },
        { left: 'terraform destroy', right: 'Elimina todos los recursos' },
      ],
    },
    {
      id: 'intro-5',
      title: 'Clasifica cada elemento en su categoría',
      type: 'classify',
      points: 4,
      explanation: 'hashicorp/aws y hashicorp/google son providers, lifecycle y dynamic son reserved keywords, plan y apply son commands.',
      categories: ['Providers', 'Reserved Keywords', 'Commands'],
      classifyItems: [
        { text: 'hashicorp/aws', category: 'Providers' },
        { text: 'hashicorp/google', category: 'Providers' },
        { text: 'lifecycle', category: 'Reserved Keywords' },
        { text: 'dynamic', category: 'Reserved Keywords' },
        { text: 'plan', category: 'Commands' },
        { text: 'apply', category: 'Commands' },
      ],
    },
  ],
};
